name: Create AWS Lightsail Instance

on:
  workflow_dispatch:

jobs:
  create-lightsail-instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use the appropriate Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "ap-south-1"
        
    - name: Run Python Script
      env:
        AWS_REGION: ${AWS_REGION}
      run: python script.py

    - name: Wait for Instance to be Running
      run: |
        INSTANCE_NAME="saad-lightsail-instance"
        STATE="pending"
        while [ "$STATE" != "running" ]; do
          sleep 60
          STATE=$(aws lightsail get-instance-state --instance-name $INSTANCE_NAME --query 'state.name' --output text)
          echo "Current state: $STATE"
        done

    - name: Get Instance IP Address
      run: |
        INSTANCE_NAME="saad-lightsail-instance"
        IP_ADDRESS=$(aws lightsail get-instance --instance-name $INSTANCE_NAME --query 'instance.publicIpAddress' --output text)
        echo "Instance IP Address: $IP_ADDRESS"
